version: '3.8'

services:
  fastapi:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: unless-stopped  # More sensible restart policy
    mem_limit: 400m  # Hard memory limit
    cpus: 0.5
