name: Build Docker & Deploy to EC2

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-push:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/rishram-vocabulary:latest

  deploy:
    name: Deploy on EC2
    runs-on: [self-hosted]  # Assumes you have a self-hosted runner on EC2
    needs: build-and-push

    steps:
      - name: Pull and Restart App
        run: |
          cd ~/RishRam-Vocabulary
          git pull origin main || true
          docker compose pull
          docker compose down
          docker compose up -d --remove-orphans
