name: Build Docker & Deploy to EC2

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-push:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/rishramML:${{ github.sha }} .
          docker push ${{ secrets.DOCKER_USERNAME }}/rishramML:${{ github.sha }}
        env:
          TAG: ${{ github.sha }}

  deploy:
    name: Deploy on EC2
    runs-on: [self-hosted]  
    needs: build-and-push

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Deploy to EC2
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          docker-compose down
          docker-compose up -d
